# Generated by Django 2.0.3 on 2020-04-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_pizza_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('n_addons', models.IntegerField(default=0)),
                ('is_special', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allowed_for', models.ManyToManyField(blank=True, related_name='allowed_addons', to='orders.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderextra',
            name='menu_extra',
        ),
        migrations.RemoveField(
            model_name='orderextra',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderpizza',
            name='menu_pizza',
        ),
        migrations.RemoveField(
            model_name='orderpizza',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpizzatopping',
            name='menu_topping',
        ),
        migrations.RemoveField(
            model_name='orderpizzatopping',
            name='order_pizza',
        ),
        migrations.RemoveField(
            model_name='standardorderitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='standardorderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderExtra',
        ),
        migrations.DeleteModel(
            name='OrderPizza',
        ),
        migrations.DeleteModel(
            name='OrderPizzaTopping',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaTopping',
        ),
        migrations.DeleteModel(
            name='StandardMenuItem',
        ),
        migrations.DeleteModel(
            name='StandardOrderItem',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.Size'),
        ),
    ]
