# Generated by Django 2.0.3 on 2020-04-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200412_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.Size'),
        ),
    ]
