# Generated by Django 2.0.3 on 2020-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200412_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_pizza_category',
            field=models.BooleanField(default=False),
        ),
    ]
