# Generated by Django 2.2.6 on 2020-05-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200502_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time_estimate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CardOnline', 'Online by Card'), ('CashOnDelivery', 'Cash on Delivery'), ('CardOnDelivery', 'Card on Delivery')], max_length=16, null=True),
        ),
    ]
