# Generated by Django 2.2.6 on 2020-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200511_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time_estimate',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_estimate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
