# Generated by Django 2.2.6 on 2020-06-03 06:51

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200531_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_id', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.Order')),
            ],
            bases=(orders.models.StandardStrMixin, models.Model),
        ),
    ]
